#include <bits/stdc++.h>

using namespace std;

int main() {
    /*
        APPEND: TODO/FIX by \inf+ AD:
        //int -> bigint?
    */
    mt19937 rnd(time(0));//APPEND
    //WHO APPEND
    GAMBLING_BANDIT_STRATEGIES_RL_MAGICK_VERSUS_CASINO_AFRICAN_VODOU;
    OMNIPOTENCE_PARADOX_QUIMBANDA_PORTAL_THE_BEAST_THE_LEMA_ORDERS_FUTURE_MAGICK_INTO_POLLAND_BALLS_ANNOYING_ORANGE(ARCHANGEL_MICHAEL);
    //AGI ASI AGI ASI WHICH? HOW MANY? ORDER? APPEND ABOVE
    //WHO ABOVE?
    //APPEND above?
}
